/*
SORACOM API

SORACOM API v1

API version: VERSION_PLACEHOLDER
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package api

import (
	"encoding/json"
)

// CreateEstimatedCouponRequest struct for CreateEstimatedCouponRequest
type CreateEstimatedCouponRequest struct {
	// Amount
	Amount float64 `json:"amount"`
}

// NewCreateEstimatedCouponRequest instantiates a new CreateEstimatedCouponRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreateEstimatedCouponRequest(amount float64) *CreateEstimatedCouponRequest {
	this := CreateEstimatedCouponRequest{}
	this.Amount = amount
	return &this
}

// NewCreateEstimatedCouponRequestWithDefaults instantiates a new CreateEstimatedCouponRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreateEstimatedCouponRequestWithDefaults() *CreateEstimatedCouponRequest {
	this := CreateEstimatedCouponRequest{}
	return &this
}

// GetAmount returns the Amount field value
func (o *CreateEstimatedCouponRequest) GetAmount() float64 {
	if o == nil {
		var ret float64
		return ret
	}

	return o.Amount
}

// GetAmountOk returns a tuple with the Amount field value
// and a boolean to check if the value has been set.
func (o *CreateEstimatedCouponRequest) GetAmountOk() (*float64, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.Amount, true
}

// SetAmount sets field value
func (o *CreateEstimatedCouponRequest) SetAmount(v float64) {
	o.Amount = v
}

func (o CreateEstimatedCouponRequest) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["amount"] = o.Amount
	}
	return json.Marshal(toSerialize)
}

type NullableCreateEstimatedCouponRequest struct {
	value *CreateEstimatedCouponRequest
	isSet bool
}

func (v NullableCreateEstimatedCouponRequest) Get() *CreateEstimatedCouponRequest {
	return v.value
}

func (v *NullableCreateEstimatedCouponRequest) Set(val *CreateEstimatedCouponRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableCreateEstimatedCouponRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableCreateEstimatedCouponRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreateEstimatedCouponRequest(val *CreateEstimatedCouponRequest) *NullableCreateEstimatedCouponRequest {
	return &NullableCreateEstimatedCouponRequest{value: val, isSet: true}
}

func (v NullableCreateEstimatedCouponRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreateEstimatedCouponRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


