/*
SORACOM API

SORACOM API v1

API version: VERSION_PLACEHOLDER
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package api

import (
	"encoding/json"
)

// CreateOrUpdateRoleRequest struct for CreateOrUpdateRoleRequest
type CreateOrUpdateRoleRequest struct {
	Description *string `json:"description,omitempty"`
	// PermissionのJSON
	Permission string `json:"permission"`
}

// NewCreateOrUpdateRoleRequest instantiates a new CreateOrUpdateRoleRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreateOrUpdateRoleRequest(permission string) *CreateOrUpdateRoleRequest {
	this := CreateOrUpdateRoleRequest{}
	this.Permission = permission
	return &this
}

// NewCreateOrUpdateRoleRequestWithDefaults instantiates a new CreateOrUpdateRoleRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreateOrUpdateRoleRequestWithDefaults() *CreateOrUpdateRoleRequest {
	this := CreateOrUpdateRoleRequest{}
	return &this
}

// GetDescription returns the Description field value if set, zero value otherwise.
func (o *CreateOrUpdateRoleRequest) GetDescription() string {
	if o == nil || o.Description == nil {
		var ret string
		return ret
	}
	return *o.Description
}

// GetDescriptionOk returns a tuple with the Description field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateOrUpdateRoleRequest) GetDescriptionOk() (*string, bool) {
	if o == nil || o.Description == nil {
		return nil, false
	}
	return o.Description, true
}

// HasDescription returns a boolean if a field has been set.
func (o *CreateOrUpdateRoleRequest) HasDescription() bool {
	if o != nil && o.Description != nil {
		return true
	}

	return false
}

// SetDescription gets a reference to the given string and assigns it to the Description field.
func (o *CreateOrUpdateRoleRequest) SetDescription(v string) {
	o.Description = &v
}

// GetPermission returns the Permission field value
func (o *CreateOrUpdateRoleRequest) GetPermission() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Permission
}

// GetPermissionOk returns a tuple with the Permission field value
// and a boolean to check if the value has been set.
func (o *CreateOrUpdateRoleRequest) GetPermissionOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.Permission, true
}

// SetPermission sets field value
func (o *CreateOrUpdateRoleRequest) SetPermission(v string) {
	o.Permission = v
}

func (o CreateOrUpdateRoleRequest) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Description != nil {
		toSerialize["description"] = o.Description
	}
	if true {
		toSerialize["permission"] = o.Permission
	}
	return json.Marshal(toSerialize)
}

type NullableCreateOrUpdateRoleRequest struct {
	value *CreateOrUpdateRoleRequest
	isSet bool
}

func (v NullableCreateOrUpdateRoleRequest) Get() *CreateOrUpdateRoleRequest {
	return v.value
}

func (v *NullableCreateOrUpdateRoleRequest) Set(val *CreateOrUpdateRoleRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableCreateOrUpdateRoleRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableCreateOrUpdateRoleRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreateOrUpdateRoleRequest(val *CreateOrUpdateRoleRequest) *NullableCreateOrUpdateRoleRequest {
	return &NullableCreateOrUpdateRoleRequest{value: val, isSet: true}
}

func (v NullableCreateOrUpdateRoleRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreateOrUpdateRoleRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


