/*
SORACOM API

SORACOM API v1

API version: VERSION_PLACEHOLDER
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package api

import (
	"encoding/json"
)

// FunnelInfoteriaPlatioDestination struct for FunnelInfoteriaPlatioDestination
type FunnelInfoteriaPlatioDestination struct {
	ApplicationId *string `json:"applicationId,omitempty"`
	CollectionId *string `json:"collectionId,omitempty"`
	PassAll *bool `json:"passAll,omitempty"`
	Provider *string `json:"provider,omitempty"`
	ResourceUrl *string `json:"resourceUrl,omitempty"`
	Service *string `json:"service,omitempty"`
	Values *string `json:"values,omitempty"`
}

// NewFunnelInfoteriaPlatioDestination instantiates a new FunnelInfoteriaPlatioDestination object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewFunnelInfoteriaPlatioDestination() *FunnelInfoteriaPlatioDestination {
	this := FunnelInfoteriaPlatioDestination{}
	return &this
}

// NewFunnelInfoteriaPlatioDestinationWithDefaults instantiates a new FunnelInfoteriaPlatioDestination object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewFunnelInfoteriaPlatioDestinationWithDefaults() *FunnelInfoteriaPlatioDestination {
	this := FunnelInfoteriaPlatioDestination{}
	return &this
}

// GetApplicationId returns the ApplicationId field value if set, zero value otherwise.
func (o *FunnelInfoteriaPlatioDestination) GetApplicationId() string {
	if o == nil || o.ApplicationId == nil {
		var ret string
		return ret
	}
	return *o.ApplicationId
}

// GetApplicationIdOk returns a tuple with the ApplicationId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FunnelInfoteriaPlatioDestination) GetApplicationIdOk() (*string, bool) {
	if o == nil || o.ApplicationId == nil {
		return nil, false
	}
	return o.ApplicationId, true
}

// HasApplicationId returns a boolean if a field has been set.
func (o *FunnelInfoteriaPlatioDestination) HasApplicationId() bool {
	if o != nil && o.ApplicationId != nil {
		return true
	}

	return false
}

// SetApplicationId gets a reference to the given string and assigns it to the ApplicationId field.
func (o *FunnelInfoteriaPlatioDestination) SetApplicationId(v string) {
	o.ApplicationId = &v
}

// GetCollectionId returns the CollectionId field value if set, zero value otherwise.
func (o *FunnelInfoteriaPlatioDestination) GetCollectionId() string {
	if o == nil || o.CollectionId == nil {
		var ret string
		return ret
	}
	return *o.CollectionId
}

// GetCollectionIdOk returns a tuple with the CollectionId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FunnelInfoteriaPlatioDestination) GetCollectionIdOk() (*string, bool) {
	if o == nil || o.CollectionId == nil {
		return nil, false
	}
	return o.CollectionId, true
}

// HasCollectionId returns a boolean if a field has been set.
func (o *FunnelInfoteriaPlatioDestination) HasCollectionId() bool {
	if o != nil && o.CollectionId != nil {
		return true
	}

	return false
}

// SetCollectionId gets a reference to the given string and assigns it to the CollectionId field.
func (o *FunnelInfoteriaPlatioDestination) SetCollectionId(v string) {
	o.CollectionId = &v
}

// GetPassAll returns the PassAll field value if set, zero value otherwise.
func (o *FunnelInfoteriaPlatioDestination) GetPassAll() bool {
	if o == nil || o.PassAll == nil {
		var ret bool
		return ret
	}
	return *o.PassAll
}

// GetPassAllOk returns a tuple with the PassAll field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FunnelInfoteriaPlatioDestination) GetPassAllOk() (*bool, bool) {
	if o == nil || o.PassAll == nil {
		return nil, false
	}
	return o.PassAll, true
}

// HasPassAll returns a boolean if a field has been set.
func (o *FunnelInfoteriaPlatioDestination) HasPassAll() bool {
	if o != nil && o.PassAll != nil {
		return true
	}

	return false
}

// SetPassAll gets a reference to the given bool and assigns it to the PassAll field.
func (o *FunnelInfoteriaPlatioDestination) SetPassAll(v bool) {
	o.PassAll = &v
}

// GetProvider returns the Provider field value if set, zero value otherwise.
func (o *FunnelInfoteriaPlatioDestination) GetProvider() string {
	if o == nil || o.Provider == nil {
		var ret string
		return ret
	}
	return *o.Provider
}

// GetProviderOk returns a tuple with the Provider field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FunnelInfoteriaPlatioDestination) GetProviderOk() (*string, bool) {
	if o == nil || o.Provider == nil {
		return nil, false
	}
	return o.Provider, true
}

// HasProvider returns a boolean if a field has been set.
func (o *FunnelInfoteriaPlatioDestination) HasProvider() bool {
	if o != nil && o.Provider != nil {
		return true
	}

	return false
}

// SetProvider gets a reference to the given string and assigns it to the Provider field.
func (o *FunnelInfoteriaPlatioDestination) SetProvider(v string) {
	o.Provider = &v
}

// GetResourceUrl returns the ResourceUrl field value if set, zero value otherwise.
func (o *FunnelInfoteriaPlatioDestination) GetResourceUrl() string {
	if o == nil || o.ResourceUrl == nil {
		var ret string
		return ret
	}
	return *o.ResourceUrl
}

// GetResourceUrlOk returns a tuple with the ResourceUrl field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FunnelInfoteriaPlatioDestination) GetResourceUrlOk() (*string, bool) {
	if o == nil || o.ResourceUrl == nil {
		return nil, false
	}
	return o.ResourceUrl, true
}

// HasResourceUrl returns a boolean if a field has been set.
func (o *FunnelInfoteriaPlatioDestination) HasResourceUrl() bool {
	if o != nil && o.ResourceUrl != nil {
		return true
	}

	return false
}

// SetResourceUrl gets a reference to the given string and assigns it to the ResourceUrl field.
func (o *FunnelInfoteriaPlatioDestination) SetResourceUrl(v string) {
	o.ResourceUrl = &v
}

// GetService returns the Service field value if set, zero value otherwise.
func (o *FunnelInfoteriaPlatioDestination) GetService() string {
	if o == nil || o.Service == nil {
		var ret string
		return ret
	}
	return *o.Service
}

// GetServiceOk returns a tuple with the Service field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FunnelInfoteriaPlatioDestination) GetServiceOk() (*string, bool) {
	if o == nil || o.Service == nil {
		return nil, false
	}
	return o.Service, true
}

// HasService returns a boolean if a field has been set.
func (o *FunnelInfoteriaPlatioDestination) HasService() bool {
	if o != nil && o.Service != nil {
		return true
	}

	return false
}

// SetService gets a reference to the given string and assigns it to the Service field.
func (o *FunnelInfoteriaPlatioDestination) SetService(v string) {
	o.Service = &v
}

// GetValues returns the Values field value if set, zero value otherwise.
func (o *FunnelInfoteriaPlatioDestination) GetValues() string {
	if o == nil || o.Values == nil {
		var ret string
		return ret
	}
	return *o.Values
}

// GetValuesOk returns a tuple with the Values field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FunnelInfoteriaPlatioDestination) GetValuesOk() (*string, bool) {
	if o == nil || o.Values == nil {
		return nil, false
	}
	return o.Values, true
}

// HasValues returns a boolean if a field has been set.
func (o *FunnelInfoteriaPlatioDestination) HasValues() bool {
	if o != nil && o.Values != nil {
		return true
	}

	return false
}

// SetValues gets a reference to the given string and assigns it to the Values field.
func (o *FunnelInfoteriaPlatioDestination) SetValues(v string) {
	o.Values = &v
}

func (o FunnelInfoteriaPlatioDestination) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.ApplicationId != nil {
		toSerialize["applicationId"] = o.ApplicationId
	}
	if o.CollectionId != nil {
		toSerialize["collectionId"] = o.CollectionId
	}
	if o.PassAll != nil {
		toSerialize["passAll"] = o.PassAll
	}
	if o.Provider != nil {
		toSerialize["provider"] = o.Provider
	}
	if o.ResourceUrl != nil {
		toSerialize["resourceUrl"] = o.ResourceUrl
	}
	if o.Service != nil {
		toSerialize["service"] = o.Service
	}
	if o.Values != nil {
		toSerialize["values"] = o.Values
	}
	return json.Marshal(toSerialize)
}

type NullableFunnelInfoteriaPlatioDestination struct {
	value *FunnelInfoteriaPlatioDestination
	isSet bool
}

func (v NullableFunnelInfoteriaPlatioDestination) Get() *FunnelInfoteriaPlatioDestination {
	return v.value
}

func (v *NullableFunnelInfoteriaPlatioDestination) Set(val *FunnelInfoteriaPlatioDestination) {
	v.value = val
	v.isSet = true
}

func (v NullableFunnelInfoteriaPlatioDestination) IsSet() bool {
	return v.isSet
}

func (v *NullableFunnelInfoteriaPlatioDestination) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableFunnelInfoteriaPlatioDestination(val *FunnelInfoteriaPlatioDestination) *NullableFunnelInfoteriaPlatioDestination {
	return &NullableFunnelInfoteriaPlatioDestination{value: val, isSet: true}
}

func (v NullableFunnelInfoteriaPlatioDestination) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableFunnelInfoteriaPlatioDestination) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


