/*
SORACOM API

SORACOM API v1

API version: VERSION_PLACEHOLDER
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package api

import (
	"encoding/json"
)

// CouponResponse struct for CouponResponse
type CouponResponse struct {
	// Amount
	Amount *float64 `json:"amount,omitempty"`
	// Balance
	Balance *float64 `json:"balance,omitempty"`
	// Item
	BillItemName *string `json:"billItemName,omitempty"`
	// Coupon code
	CouponCode *string `json:"couponCode,omitempty"`
	// Expiry month
	ExpiryYearMonth *string `json:"expiryYearMonth,omitempty"`
	// Order ID
	OrderId *string `json:"orderId,omitempty"`
}

// NewCouponResponse instantiates a new CouponResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCouponResponse() *CouponResponse {
	this := CouponResponse{}
	return &this
}

// NewCouponResponseWithDefaults instantiates a new CouponResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCouponResponseWithDefaults() *CouponResponse {
	this := CouponResponse{}
	return &this
}

// GetAmount returns the Amount field value if set, zero value otherwise.
func (o *CouponResponse) GetAmount() float64 {
	if o == nil || o.Amount == nil {
		var ret float64
		return ret
	}
	return *o.Amount
}

// GetAmountOk returns a tuple with the Amount field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CouponResponse) GetAmountOk() (*float64, bool) {
	if o == nil || o.Amount == nil {
		return nil, false
	}
	return o.Amount, true
}

// HasAmount returns a boolean if a field has been set.
func (o *CouponResponse) HasAmount() bool {
	if o != nil && o.Amount != nil {
		return true
	}

	return false
}

// SetAmount gets a reference to the given float64 and assigns it to the Amount field.
func (o *CouponResponse) SetAmount(v float64) {
	o.Amount = &v
}

// GetBalance returns the Balance field value if set, zero value otherwise.
func (o *CouponResponse) GetBalance() float64 {
	if o == nil || o.Balance == nil {
		var ret float64
		return ret
	}
	return *o.Balance
}

// GetBalanceOk returns a tuple with the Balance field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CouponResponse) GetBalanceOk() (*float64, bool) {
	if o == nil || o.Balance == nil {
		return nil, false
	}
	return o.Balance, true
}

// HasBalance returns a boolean if a field has been set.
func (o *CouponResponse) HasBalance() bool {
	if o != nil && o.Balance != nil {
		return true
	}

	return false
}

// SetBalance gets a reference to the given float64 and assigns it to the Balance field.
func (o *CouponResponse) SetBalance(v float64) {
	o.Balance = &v
}

// GetBillItemName returns the BillItemName field value if set, zero value otherwise.
func (o *CouponResponse) GetBillItemName() string {
	if o == nil || o.BillItemName == nil {
		var ret string
		return ret
	}
	return *o.BillItemName
}

// GetBillItemNameOk returns a tuple with the BillItemName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CouponResponse) GetBillItemNameOk() (*string, bool) {
	if o == nil || o.BillItemName == nil {
		return nil, false
	}
	return o.BillItemName, true
}

// HasBillItemName returns a boolean if a field has been set.
func (o *CouponResponse) HasBillItemName() bool {
	if o != nil && o.BillItemName != nil {
		return true
	}

	return false
}

// SetBillItemName gets a reference to the given string and assigns it to the BillItemName field.
func (o *CouponResponse) SetBillItemName(v string) {
	o.BillItemName = &v
}

// GetCouponCode returns the CouponCode field value if set, zero value otherwise.
func (o *CouponResponse) GetCouponCode() string {
	if o == nil || o.CouponCode == nil {
		var ret string
		return ret
	}
	return *o.CouponCode
}

// GetCouponCodeOk returns a tuple with the CouponCode field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CouponResponse) GetCouponCodeOk() (*string, bool) {
	if o == nil || o.CouponCode == nil {
		return nil, false
	}
	return o.CouponCode, true
}

// HasCouponCode returns a boolean if a field has been set.
func (o *CouponResponse) HasCouponCode() bool {
	if o != nil && o.CouponCode != nil {
		return true
	}

	return false
}

// SetCouponCode gets a reference to the given string and assigns it to the CouponCode field.
func (o *CouponResponse) SetCouponCode(v string) {
	o.CouponCode = &v
}

// GetExpiryYearMonth returns the ExpiryYearMonth field value if set, zero value otherwise.
func (o *CouponResponse) GetExpiryYearMonth() string {
	if o == nil || o.ExpiryYearMonth == nil {
		var ret string
		return ret
	}
	return *o.ExpiryYearMonth
}

// GetExpiryYearMonthOk returns a tuple with the ExpiryYearMonth field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CouponResponse) GetExpiryYearMonthOk() (*string, bool) {
	if o == nil || o.ExpiryYearMonth == nil {
		return nil, false
	}
	return o.ExpiryYearMonth, true
}

// HasExpiryYearMonth returns a boolean if a field has been set.
func (o *CouponResponse) HasExpiryYearMonth() bool {
	if o != nil && o.ExpiryYearMonth != nil {
		return true
	}

	return false
}

// SetExpiryYearMonth gets a reference to the given string and assigns it to the ExpiryYearMonth field.
func (o *CouponResponse) SetExpiryYearMonth(v string) {
	o.ExpiryYearMonth = &v
}

// GetOrderId returns the OrderId field value if set, zero value otherwise.
func (o *CouponResponse) GetOrderId() string {
	if o == nil || o.OrderId == nil {
		var ret string
		return ret
	}
	return *o.OrderId
}

// GetOrderIdOk returns a tuple with the OrderId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CouponResponse) GetOrderIdOk() (*string, bool) {
	if o == nil || o.OrderId == nil {
		return nil, false
	}
	return o.OrderId, true
}

// HasOrderId returns a boolean if a field has been set.
func (o *CouponResponse) HasOrderId() bool {
	if o != nil && o.OrderId != nil {
		return true
	}

	return false
}

// SetOrderId gets a reference to the given string and assigns it to the OrderId field.
func (o *CouponResponse) SetOrderId(v string) {
	o.OrderId = &v
}

func (o CouponResponse) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Amount != nil {
		toSerialize["amount"] = o.Amount
	}
	if o.Balance != nil {
		toSerialize["balance"] = o.Balance
	}
	if o.BillItemName != nil {
		toSerialize["billItemName"] = o.BillItemName
	}
	if o.CouponCode != nil {
		toSerialize["couponCode"] = o.CouponCode
	}
	if o.ExpiryYearMonth != nil {
		toSerialize["expiryYearMonth"] = o.ExpiryYearMonth
	}
	if o.OrderId != nil {
		toSerialize["orderId"] = o.OrderId
	}
	return json.Marshal(toSerialize)
}

type NullableCouponResponse struct {
	value *CouponResponse
	isSet bool
}

func (v NullableCouponResponse) Get() *CouponResponse {
	return v.value
}

func (v *NullableCouponResponse) Set(val *CouponResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableCouponResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableCouponResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCouponResponse(val *CouponResponse) *NullableCouponResponse {
	return &NullableCouponResponse{value: val, isSet: true}
}

func (v NullableCouponResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCouponResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


