/*
SORACOM API

SORACOM API v1

API version: VERSION_PLACEHOLDER
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package api

import (
	"encoding/json"
)

// SigfoxRegistrationRequest struct for SigfoxRegistrationRequest
type SigfoxRegistrationRequest struct {
	RegistrationSecret *string `json:"registrationSecret,omitempty"`
	Tags *map[string]string `json:"tags,omitempty"`
}

// NewSigfoxRegistrationRequest instantiates a new SigfoxRegistrationRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSigfoxRegistrationRequest() *SigfoxRegistrationRequest {
	this := SigfoxRegistrationRequest{}
	return &this
}

// NewSigfoxRegistrationRequestWithDefaults instantiates a new SigfoxRegistrationRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSigfoxRegistrationRequestWithDefaults() *SigfoxRegistrationRequest {
	this := SigfoxRegistrationRequest{}
	return &this
}

// GetRegistrationSecret returns the RegistrationSecret field value if set, zero value otherwise.
func (o *SigfoxRegistrationRequest) GetRegistrationSecret() string {
	if o == nil || o.RegistrationSecret == nil {
		var ret string
		return ret
	}
	return *o.RegistrationSecret
}

// GetRegistrationSecretOk returns a tuple with the RegistrationSecret field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SigfoxRegistrationRequest) GetRegistrationSecretOk() (*string, bool) {
	if o == nil || o.RegistrationSecret == nil {
		return nil, false
	}
	return o.RegistrationSecret, true
}

// HasRegistrationSecret returns a boolean if a field has been set.
func (o *SigfoxRegistrationRequest) HasRegistrationSecret() bool {
	if o != nil && o.RegistrationSecret != nil {
		return true
	}

	return false
}

// SetRegistrationSecret gets a reference to the given string and assigns it to the RegistrationSecret field.
func (o *SigfoxRegistrationRequest) SetRegistrationSecret(v string) {
	o.RegistrationSecret = &v
}

// GetTags returns the Tags field value if set, zero value otherwise.
func (o *SigfoxRegistrationRequest) GetTags() map[string]string {
	if o == nil || o.Tags == nil {
		var ret map[string]string
		return ret
	}
	return *o.Tags
}

// GetTagsOk returns a tuple with the Tags field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SigfoxRegistrationRequest) GetTagsOk() (*map[string]string, bool) {
	if o == nil || o.Tags == nil {
		return nil, false
	}
	return o.Tags, true
}

// HasTags returns a boolean if a field has been set.
func (o *SigfoxRegistrationRequest) HasTags() bool {
	if o != nil && o.Tags != nil {
		return true
	}

	return false
}

// SetTags gets a reference to the given map[string]string and assigns it to the Tags field.
func (o *SigfoxRegistrationRequest) SetTags(v map[string]string) {
	o.Tags = &v
}

func (o SigfoxRegistrationRequest) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.RegistrationSecret != nil {
		toSerialize["registrationSecret"] = o.RegistrationSecret
	}
	if o.Tags != nil {
		toSerialize["tags"] = o.Tags
	}
	return json.Marshal(toSerialize)
}

type NullableSigfoxRegistrationRequest struct {
	value *SigfoxRegistrationRequest
	isSet bool
}

func (v NullableSigfoxRegistrationRequest) Get() *SigfoxRegistrationRequest {
	return v.value
}

func (v *NullableSigfoxRegistrationRequest) Set(val *SigfoxRegistrationRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableSigfoxRegistrationRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableSigfoxRegistrationRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSigfoxRegistrationRequest(val *SigfoxRegistrationRequest) *NullableSigfoxRegistrationRequest {
	return &NullableSigfoxRegistrationRequest{value: val, isSet: true}
}

func (v NullableSigfoxRegistrationRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSigfoxRegistrationRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


