/*
SORACOM API

SORACOM API v1

API version: VERSION_PLACEHOLDER
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package api

import (
	"encoding/json"
)

// GetVolumeDiscountResponse struct for GetVolumeDiscountResponse
type GetVolumeDiscountResponse struct {
	// Contract date time
	ContractDateTime *string `json:"contractDateTime,omitempty"`
	// Contract ID
	ContractId *string `json:"contractId,omitempty"`
	// Contract months
	ContractTermMonth *int32 `json:"contractTermMonth,omitempty"`
	// End date
	EndDate *string `json:"endDate,omitempty"`
	// Initial cost
	InitialCost *float64 `json:"initialCost,omitempty"`
	// Quantity
	Quantity *int32 `json:"quantity,omitempty"`
	// Start date
	StartDate *string `json:"startDate,omitempty"`
	// Status
	Status *string `json:"status,omitempty"`
	// Unit price
	UnitPrice *float64 `json:"unitPrice,omitempty"`
	// Payment type
	VolumeDiscountPaymentType *string `json:"volumeDiscountPaymentType,omitempty"`
	// Long term discount type
	VolumeDiscountType *string `json:"volumeDiscountType,omitempty"`
}

// NewGetVolumeDiscountResponse instantiates a new GetVolumeDiscountResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetVolumeDiscountResponse() *GetVolumeDiscountResponse {
	this := GetVolumeDiscountResponse{}
	var contractTermMonth int32 = 12
	this.ContractTermMonth = &contractTermMonth
	return &this
}

// NewGetVolumeDiscountResponseWithDefaults instantiates a new GetVolumeDiscountResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetVolumeDiscountResponseWithDefaults() *GetVolumeDiscountResponse {
	this := GetVolumeDiscountResponse{}
	var contractTermMonth int32 = 12
	this.ContractTermMonth = &contractTermMonth
	return &this
}

// GetContractDateTime returns the ContractDateTime field value if set, zero value otherwise.
func (o *GetVolumeDiscountResponse) GetContractDateTime() string {
	if o == nil || o.ContractDateTime == nil {
		var ret string
		return ret
	}
	return *o.ContractDateTime
}

// GetContractDateTimeOk returns a tuple with the ContractDateTime field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetVolumeDiscountResponse) GetContractDateTimeOk() (*string, bool) {
	if o == nil || o.ContractDateTime == nil {
		return nil, false
	}
	return o.ContractDateTime, true
}

// HasContractDateTime returns a boolean if a field has been set.
func (o *GetVolumeDiscountResponse) HasContractDateTime() bool {
	if o != nil && o.ContractDateTime != nil {
		return true
	}

	return false
}

// SetContractDateTime gets a reference to the given string and assigns it to the ContractDateTime field.
func (o *GetVolumeDiscountResponse) SetContractDateTime(v string) {
	o.ContractDateTime = &v
}

// GetContractId returns the ContractId field value if set, zero value otherwise.
func (o *GetVolumeDiscountResponse) GetContractId() string {
	if o == nil || o.ContractId == nil {
		var ret string
		return ret
	}
	return *o.ContractId
}

// GetContractIdOk returns a tuple with the ContractId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetVolumeDiscountResponse) GetContractIdOk() (*string, bool) {
	if o == nil || o.ContractId == nil {
		return nil, false
	}
	return o.ContractId, true
}

// HasContractId returns a boolean if a field has been set.
func (o *GetVolumeDiscountResponse) HasContractId() bool {
	if o != nil && o.ContractId != nil {
		return true
	}

	return false
}

// SetContractId gets a reference to the given string and assigns it to the ContractId field.
func (o *GetVolumeDiscountResponse) SetContractId(v string) {
	o.ContractId = &v
}

// GetContractTermMonth returns the ContractTermMonth field value if set, zero value otherwise.
func (o *GetVolumeDiscountResponse) GetContractTermMonth() int32 {
	if o == nil || o.ContractTermMonth == nil {
		var ret int32
		return ret
	}
	return *o.ContractTermMonth
}

// GetContractTermMonthOk returns a tuple with the ContractTermMonth field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetVolumeDiscountResponse) GetContractTermMonthOk() (*int32, bool) {
	if o == nil || o.ContractTermMonth == nil {
		return nil, false
	}
	return o.ContractTermMonth, true
}

// HasContractTermMonth returns a boolean if a field has been set.
func (o *GetVolumeDiscountResponse) HasContractTermMonth() bool {
	if o != nil && o.ContractTermMonth != nil {
		return true
	}

	return false
}

// SetContractTermMonth gets a reference to the given int32 and assigns it to the ContractTermMonth field.
func (o *GetVolumeDiscountResponse) SetContractTermMonth(v int32) {
	o.ContractTermMonth = &v
}

// GetEndDate returns the EndDate field value if set, zero value otherwise.
func (o *GetVolumeDiscountResponse) GetEndDate() string {
	if o == nil || o.EndDate == nil {
		var ret string
		return ret
	}
	return *o.EndDate
}

// GetEndDateOk returns a tuple with the EndDate field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetVolumeDiscountResponse) GetEndDateOk() (*string, bool) {
	if o == nil || o.EndDate == nil {
		return nil, false
	}
	return o.EndDate, true
}

// HasEndDate returns a boolean if a field has been set.
func (o *GetVolumeDiscountResponse) HasEndDate() bool {
	if o != nil && o.EndDate != nil {
		return true
	}

	return false
}

// SetEndDate gets a reference to the given string and assigns it to the EndDate field.
func (o *GetVolumeDiscountResponse) SetEndDate(v string) {
	o.EndDate = &v
}

// GetInitialCost returns the InitialCost field value if set, zero value otherwise.
func (o *GetVolumeDiscountResponse) GetInitialCost() float64 {
	if o == nil || o.InitialCost == nil {
		var ret float64
		return ret
	}
	return *o.InitialCost
}

// GetInitialCostOk returns a tuple with the InitialCost field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetVolumeDiscountResponse) GetInitialCostOk() (*float64, bool) {
	if o == nil || o.InitialCost == nil {
		return nil, false
	}
	return o.InitialCost, true
}

// HasInitialCost returns a boolean if a field has been set.
func (o *GetVolumeDiscountResponse) HasInitialCost() bool {
	if o != nil && o.InitialCost != nil {
		return true
	}

	return false
}

// SetInitialCost gets a reference to the given float64 and assigns it to the InitialCost field.
func (o *GetVolumeDiscountResponse) SetInitialCost(v float64) {
	o.InitialCost = &v
}

// GetQuantity returns the Quantity field value if set, zero value otherwise.
func (o *GetVolumeDiscountResponse) GetQuantity() int32 {
	if o == nil || o.Quantity == nil {
		var ret int32
		return ret
	}
	return *o.Quantity
}

// GetQuantityOk returns a tuple with the Quantity field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetVolumeDiscountResponse) GetQuantityOk() (*int32, bool) {
	if o == nil || o.Quantity == nil {
		return nil, false
	}
	return o.Quantity, true
}

// HasQuantity returns a boolean if a field has been set.
func (o *GetVolumeDiscountResponse) HasQuantity() bool {
	if o != nil && o.Quantity != nil {
		return true
	}

	return false
}

// SetQuantity gets a reference to the given int32 and assigns it to the Quantity field.
func (o *GetVolumeDiscountResponse) SetQuantity(v int32) {
	o.Quantity = &v
}

// GetStartDate returns the StartDate field value if set, zero value otherwise.
func (o *GetVolumeDiscountResponse) GetStartDate() string {
	if o == nil || o.StartDate == nil {
		var ret string
		return ret
	}
	return *o.StartDate
}

// GetStartDateOk returns a tuple with the StartDate field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetVolumeDiscountResponse) GetStartDateOk() (*string, bool) {
	if o == nil || o.StartDate == nil {
		return nil, false
	}
	return o.StartDate, true
}

// HasStartDate returns a boolean if a field has been set.
func (o *GetVolumeDiscountResponse) HasStartDate() bool {
	if o != nil && o.StartDate != nil {
		return true
	}

	return false
}

// SetStartDate gets a reference to the given string and assigns it to the StartDate field.
func (o *GetVolumeDiscountResponse) SetStartDate(v string) {
	o.StartDate = &v
}

// GetStatus returns the Status field value if set, zero value otherwise.
func (o *GetVolumeDiscountResponse) GetStatus() string {
	if o == nil || o.Status == nil {
		var ret string
		return ret
	}
	return *o.Status
}

// GetStatusOk returns a tuple with the Status field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetVolumeDiscountResponse) GetStatusOk() (*string, bool) {
	if o == nil || o.Status == nil {
		return nil, false
	}
	return o.Status, true
}

// HasStatus returns a boolean if a field has been set.
func (o *GetVolumeDiscountResponse) HasStatus() bool {
	if o != nil && o.Status != nil {
		return true
	}

	return false
}

// SetStatus gets a reference to the given string and assigns it to the Status field.
func (o *GetVolumeDiscountResponse) SetStatus(v string) {
	o.Status = &v
}

// GetUnitPrice returns the UnitPrice field value if set, zero value otherwise.
func (o *GetVolumeDiscountResponse) GetUnitPrice() float64 {
	if o == nil || o.UnitPrice == nil {
		var ret float64
		return ret
	}
	return *o.UnitPrice
}

// GetUnitPriceOk returns a tuple with the UnitPrice field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetVolumeDiscountResponse) GetUnitPriceOk() (*float64, bool) {
	if o == nil || o.UnitPrice == nil {
		return nil, false
	}
	return o.UnitPrice, true
}

// HasUnitPrice returns a boolean if a field has been set.
func (o *GetVolumeDiscountResponse) HasUnitPrice() bool {
	if o != nil && o.UnitPrice != nil {
		return true
	}

	return false
}

// SetUnitPrice gets a reference to the given float64 and assigns it to the UnitPrice field.
func (o *GetVolumeDiscountResponse) SetUnitPrice(v float64) {
	o.UnitPrice = &v
}

// GetVolumeDiscountPaymentType returns the VolumeDiscountPaymentType field value if set, zero value otherwise.
func (o *GetVolumeDiscountResponse) GetVolumeDiscountPaymentType() string {
	if o == nil || o.VolumeDiscountPaymentType == nil {
		var ret string
		return ret
	}
	return *o.VolumeDiscountPaymentType
}

// GetVolumeDiscountPaymentTypeOk returns a tuple with the VolumeDiscountPaymentType field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetVolumeDiscountResponse) GetVolumeDiscountPaymentTypeOk() (*string, bool) {
	if o == nil || o.VolumeDiscountPaymentType == nil {
		return nil, false
	}
	return o.VolumeDiscountPaymentType, true
}

// HasVolumeDiscountPaymentType returns a boolean if a field has been set.
func (o *GetVolumeDiscountResponse) HasVolumeDiscountPaymentType() bool {
	if o != nil && o.VolumeDiscountPaymentType != nil {
		return true
	}

	return false
}

// SetVolumeDiscountPaymentType gets a reference to the given string and assigns it to the VolumeDiscountPaymentType field.
func (o *GetVolumeDiscountResponse) SetVolumeDiscountPaymentType(v string) {
	o.VolumeDiscountPaymentType = &v
}

// GetVolumeDiscountType returns the VolumeDiscountType field value if set, zero value otherwise.
func (o *GetVolumeDiscountResponse) GetVolumeDiscountType() string {
	if o == nil || o.VolumeDiscountType == nil {
		var ret string
		return ret
	}
	return *o.VolumeDiscountType
}

// GetVolumeDiscountTypeOk returns a tuple with the VolumeDiscountType field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetVolumeDiscountResponse) GetVolumeDiscountTypeOk() (*string, bool) {
	if o == nil || o.VolumeDiscountType == nil {
		return nil, false
	}
	return o.VolumeDiscountType, true
}

// HasVolumeDiscountType returns a boolean if a field has been set.
func (o *GetVolumeDiscountResponse) HasVolumeDiscountType() bool {
	if o != nil && o.VolumeDiscountType != nil {
		return true
	}

	return false
}

// SetVolumeDiscountType gets a reference to the given string and assigns it to the VolumeDiscountType field.
func (o *GetVolumeDiscountResponse) SetVolumeDiscountType(v string) {
	o.VolumeDiscountType = &v
}

func (o GetVolumeDiscountResponse) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.ContractDateTime != nil {
		toSerialize["contractDateTime"] = o.ContractDateTime
	}
	if o.ContractId != nil {
		toSerialize["contractId"] = o.ContractId
	}
	if o.ContractTermMonth != nil {
		toSerialize["contractTermMonth"] = o.ContractTermMonth
	}
	if o.EndDate != nil {
		toSerialize["endDate"] = o.EndDate
	}
	if o.InitialCost != nil {
		toSerialize["initialCost"] = o.InitialCost
	}
	if o.Quantity != nil {
		toSerialize["quantity"] = o.Quantity
	}
	if o.StartDate != nil {
		toSerialize["startDate"] = o.StartDate
	}
	if o.Status != nil {
		toSerialize["status"] = o.Status
	}
	if o.UnitPrice != nil {
		toSerialize["unitPrice"] = o.UnitPrice
	}
	if o.VolumeDiscountPaymentType != nil {
		toSerialize["volumeDiscountPaymentType"] = o.VolumeDiscountPaymentType
	}
	if o.VolumeDiscountType != nil {
		toSerialize["volumeDiscountType"] = o.VolumeDiscountType
	}
	return json.Marshal(toSerialize)
}

type NullableGetVolumeDiscountResponse struct {
	value *GetVolumeDiscountResponse
	isSet bool
}

func (v NullableGetVolumeDiscountResponse) Get() *GetVolumeDiscountResponse {
	return v.value
}

func (v *NullableGetVolumeDiscountResponse) Set(val *GetVolumeDiscountResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableGetVolumeDiscountResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableGetVolumeDiscountResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetVolumeDiscountResponse(val *GetVolumeDiscountResponse) *NullableGetVolumeDiscountResponse {
	return &NullableGetVolumeDiscountResponse{value: val, isSet: true}
}

func (v NullableGetVolumeDiscountResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetVolumeDiscountResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


