/*
SORACOM API

SORACOM API v1

API version: VERSION_PLACEHOLDER
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package api

import (
	"encoding/json"
)

// GetShippingAddressResponse struct for GetShippingAddressResponse
type GetShippingAddressResponse struct {
	AddressLine1 string `json:"addressLine1"`
	AddressLine2 *string `json:"addressLine2,omitempty"`
	Building *string `json:"building,omitempty"`
	City string `json:"city"`
	CompanyName *string `json:"companyName,omitempty"`
	Department *string `json:"department,omitempty"`
	FullName *string `json:"fullName,omitempty"`
	PhoneNumber string `json:"phoneNumber"`
	// 配送先ID
	ShippingAddressId string `json:"shippingAddressId"`
	// 配送先エリア
	ShippingArea string `json:"shippingArea"`
	State string `json:"state"`
	ZipCode string `json:"zipCode"`
}

// NewGetShippingAddressResponse instantiates a new GetShippingAddressResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetShippingAddressResponse(addressLine1 string, city string, phoneNumber string, shippingAddressId string, shippingArea string, state string, zipCode string) *GetShippingAddressResponse {
	this := GetShippingAddressResponse{}
	this.AddressLine1 = addressLine1
	this.City = city
	this.PhoneNumber = phoneNumber
	this.ShippingAddressId = shippingAddressId
	this.ShippingArea = shippingArea
	this.State = state
	this.ZipCode = zipCode
	return &this
}

// NewGetShippingAddressResponseWithDefaults instantiates a new GetShippingAddressResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetShippingAddressResponseWithDefaults() *GetShippingAddressResponse {
	this := GetShippingAddressResponse{}
	return &this
}

// GetAddressLine1 returns the AddressLine1 field value
func (o *GetShippingAddressResponse) GetAddressLine1() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.AddressLine1
}

// GetAddressLine1Ok returns a tuple with the AddressLine1 field value
// and a boolean to check if the value has been set.
func (o *GetShippingAddressResponse) GetAddressLine1Ok() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.AddressLine1, true
}

// SetAddressLine1 sets field value
func (o *GetShippingAddressResponse) SetAddressLine1(v string) {
	o.AddressLine1 = v
}

// GetAddressLine2 returns the AddressLine2 field value if set, zero value otherwise.
func (o *GetShippingAddressResponse) GetAddressLine2() string {
	if o == nil || o.AddressLine2 == nil {
		var ret string
		return ret
	}
	return *o.AddressLine2
}

// GetAddressLine2Ok returns a tuple with the AddressLine2 field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetShippingAddressResponse) GetAddressLine2Ok() (*string, bool) {
	if o == nil || o.AddressLine2 == nil {
		return nil, false
	}
	return o.AddressLine2, true
}

// HasAddressLine2 returns a boolean if a field has been set.
func (o *GetShippingAddressResponse) HasAddressLine2() bool {
	if o != nil && o.AddressLine2 != nil {
		return true
	}

	return false
}

// SetAddressLine2 gets a reference to the given string and assigns it to the AddressLine2 field.
func (o *GetShippingAddressResponse) SetAddressLine2(v string) {
	o.AddressLine2 = &v
}

// GetBuilding returns the Building field value if set, zero value otherwise.
func (o *GetShippingAddressResponse) GetBuilding() string {
	if o == nil || o.Building == nil {
		var ret string
		return ret
	}
	return *o.Building
}

// GetBuildingOk returns a tuple with the Building field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetShippingAddressResponse) GetBuildingOk() (*string, bool) {
	if o == nil || o.Building == nil {
		return nil, false
	}
	return o.Building, true
}

// HasBuilding returns a boolean if a field has been set.
func (o *GetShippingAddressResponse) HasBuilding() bool {
	if o != nil && o.Building != nil {
		return true
	}

	return false
}

// SetBuilding gets a reference to the given string and assigns it to the Building field.
func (o *GetShippingAddressResponse) SetBuilding(v string) {
	o.Building = &v
}

// GetCity returns the City field value
func (o *GetShippingAddressResponse) GetCity() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.City
}

// GetCityOk returns a tuple with the City field value
// and a boolean to check if the value has been set.
func (o *GetShippingAddressResponse) GetCityOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.City, true
}

// SetCity sets field value
func (o *GetShippingAddressResponse) SetCity(v string) {
	o.City = v
}

// GetCompanyName returns the CompanyName field value if set, zero value otherwise.
func (o *GetShippingAddressResponse) GetCompanyName() string {
	if o == nil || o.CompanyName == nil {
		var ret string
		return ret
	}
	return *o.CompanyName
}

// GetCompanyNameOk returns a tuple with the CompanyName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetShippingAddressResponse) GetCompanyNameOk() (*string, bool) {
	if o == nil || o.CompanyName == nil {
		return nil, false
	}
	return o.CompanyName, true
}

// HasCompanyName returns a boolean if a field has been set.
func (o *GetShippingAddressResponse) HasCompanyName() bool {
	if o != nil && o.CompanyName != nil {
		return true
	}

	return false
}

// SetCompanyName gets a reference to the given string and assigns it to the CompanyName field.
func (o *GetShippingAddressResponse) SetCompanyName(v string) {
	o.CompanyName = &v
}

// GetDepartment returns the Department field value if set, zero value otherwise.
func (o *GetShippingAddressResponse) GetDepartment() string {
	if o == nil || o.Department == nil {
		var ret string
		return ret
	}
	return *o.Department
}

// GetDepartmentOk returns a tuple with the Department field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetShippingAddressResponse) GetDepartmentOk() (*string, bool) {
	if o == nil || o.Department == nil {
		return nil, false
	}
	return o.Department, true
}

// HasDepartment returns a boolean if a field has been set.
func (o *GetShippingAddressResponse) HasDepartment() bool {
	if o != nil && o.Department != nil {
		return true
	}

	return false
}

// SetDepartment gets a reference to the given string and assigns it to the Department field.
func (o *GetShippingAddressResponse) SetDepartment(v string) {
	o.Department = &v
}

// GetFullName returns the FullName field value if set, zero value otherwise.
func (o *GetShippingAddressResponse) GetFullName() string {
	if o == nil || o.FullName == nil {
		var ret string
		return ret
	}
	return *o.FullName
}

// GetFullNameOk returns a tuple with the FullName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetShippingAddressResponse) GetFullNameOk() (*string, bool) {
	if o == nil || o.FullName == nil {
		return nil, false
	}
	return o.FullName, true
}

// HasFullName returns a boolean if a field has been set.
func (o *GetShippingAddressResponse) HasFullName() bool {
	if o != nil && o.FullName != nil {
		return true
	}

	return false
}

// SetFullName gets a reference to the given string and assigns it to the FullName field.
func (o *GetShippingAddressResponse) SetFullName(v string) {
	o.FullName = &v
}

// GetPhoneNumber returns the PhoneNumber field value
func (o *GetShippingAddressResponse) GetPhoneNumber() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.PhoneNumber
}

// GetPhoneNumberOk returns a tuple with the PhoneNumber field value
// and a boolean to check if the value has been set.
func (o *GetShippingAddressResponse) GetPhoneNumberOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.PhoneNumber, true
}

// SetPhoneNumber sets field value
func (o *GetShippingAddressResponse) SetPhoneNumber(v string) {
	o.PhoneNumber = v
}

// GetShippingAddressId returns the ShippingAddressId field value
func (o *GetShippingAddressResponse) GetShippingAddressId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ShippingAddressId
}

// GetShippingAddressIdOk returns a tuple with the ShippingAddressId field value
// and a boolean to check if the value has been set.
func (o *GetShippingAddressResponse) GetShippingAddressIdOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.ShippingAddressId, true
}

// SetShippingAddressId sets field value
func (o *GetShippingAddressResponse) SetShippingAddressId(v string) {
	o.ShippingAddressId = v
}

// GetShippingArea returns the ShippingArea field value
func (o *GetShippingAddressResponse) GetShippingArea() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ShippingArea
}

// GetShippingAreaOk returns a tuple with the ShippingArea field value
// and a boolean to check if the value has been set.
func (o *GetShippingAddressResponse) GetShippingAreaOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.ShippingArea, true
}

// SetShippingArea sets field value
func (o *GetShippingAddressResponse) SetShippingArea(v string) {
	o.ShippingArea = v
}

// GetState returns the State field value
func (o *GetShippingAddressResponse) GetState() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.State
}

// GetStateOk returns a tuple with the State field value
// and a boolean to check if the value has been set.
func (o *GetShippingAddressResponse) GetStateOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.State, true
}

// SetState sets field value
func (o *GetShippingAddressResponse) SetState(v string) {
	o.State = v
}

// GetZipCode returns the ZipCode field value
func (o *GetShippingAddressResponse) GetZipCode() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ZipCode
}

// GetZipCodeOk returns a tuple with the ZipCode field value
// and a boolean to check if the value has been set.
func (o *GetShippingAddressResponse) GetZipCodeOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.ZipCode, true
}

// SetZipCode sets field value
func (o *GetShippingAddressResponse) SetZipCode(v string) {
	o.ZipCode = v
}

func (o GetShippingAddressResponse) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["addressLine1"] = o.AddressLine1
	}
	if o.AddressLine2 != nil {
		toSerialize["addressLine2"] = o.AddressLine2
	}
	if o.Building != nil {
		toSerialize["building"] = o.Building
	}
	if true {
		toSerialize["city"] = o.City
	}
	if o.CompanyName != nil {
		toSerialize["companyName"] = o.CompanyName
	}
	if o.Department != nil {
		toSerialize["department"] = o.Department
	}
	if o.FullName != nil {
		toSerialize["fullName"] = o.FullName
	}
	if true {
		toSerialize["phoneNumber"] = o.PhoneNumber
	}
	if true {
		toSerialize["shippingAddressId"] = o.ShippingAddressId
	}
	if true {
		toSerialize["shippingArea"] = o.ShippingArea
	}
	if true {
		toSerialize["state"] = o.State
	}
	if true {
		toSerialize["zipCode"] = o.ZipCode
	}
	return json.Marshal(toSerialize)
}

type NullableGetShippingAddressResponse struct {
	value *GetShippingAddressResponse
	isSet bool
}

func (v NullableGetShippingAddressResponse) Get() *GetShippingAddressResponse {
	return v.value
}

func (v *NullableGetShippingAddressResponse) Set(val *GetShippingAddressResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableGetShippingAddressResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableGetShippingAddressResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetShippingAddressResponse(val *GetShippingAddressResponse) *NullableGetShippingAddressResponse {
	return &NullableGetShippingAddressResponse{value: val, isSet: true}
}

func (v NullableGetShippingAddressResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetShippingAddressResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


