/*
SORACOM API

SORACOM API v1

API version: VERSION_PLACEHOLDER
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package api

import (
	"encoding/json"
)

// AvailableLongTermDiscountResponse struct for AvailableLongTermDiscountResponse
type AvailableLongTermDiscountResponse struct {
	// List of available long term discounts
	AvailableLongTermDiscounts []AvailableLongTermDiscountModel `json:"availableLongTermDiscounts,omitempty"`
}

// NewAvailableLongTermDiscountResponse instantiates a new AvailableLongTermDiscountResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAvailableLongTermDiscountResponse() *AvailableLongTermDiscountResponse {
	this := AvailableLongTermDiscountResponse{}
	return &this
}

// NewAvailableLongTermDiscountResponseWithDefaults instantiates a new AvailableLongTermDiscountResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAvailableLongTermDiscountResponseWithDefaults() *AvailableLongTermDiscountResponse {
	this := AvailableLongTermDiscountResponse{}
	return &this
}

// GetAvailableLongTermDiscounts returns the AvailableLongTermDiscounts field value if set, zero value otherwise.
func (o *AvailableLongTermDiscountResponse) GetAvailableLongTermDiscounts() []AvailableLongTermDiscountModel {
	if o == nil || o.AvailableLongTermDiscounts == nil {
		var ret []AvailableLongTermDiscountModel
		return ret
	}
	return o.AvailableLongTermDiscounts
}

// GetAvailableLongTermDiscountsOk returns a tuple with the AvailableLongTermDiscounts field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AvailableLongTermDiscountResponse) GetAvailableLongTermDiscountsOk() ([]AvailableLongTermDiscountModel, bool) {
	if o == nil || o.AvailableLongTermDiscounts == nil {
		return nil, false
	}
	return o.AvailableLongTermDiscounts, true
}

// HasAvailableLongTermDiscounts returns a boolean if a field has been set.
func (o *AvailableLongTermDiscountResponse) HasAvailableLongTermDiscounts() bool {
	if o != nil && o.AvailableLongTermDiscounts != nil {
		return true
	}

	return false
}

// SetAvailableLongTermDiscounts gets a reference to the given []AvailableLongTermDiscountModel and assigns it to the AvailableLongTermDiscounts field.
func (o *AvailableLongTermDiscountResponse) SetAvailableLongTermDiscounts(v []AvailableLongTermDiscountModel) {
	o.AvailableLongTermDiscounts = v
}

func (o AvailableLongTermDiscountResponse) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.AvailableLongTermDiscounts != nil {
		toSerialize["availableLongTermDiscounts"] = o.AvailableLongTermDiscounts
	}
	return json.Marshal(toSerialize)
}

type NullableAvailableLongTermDiscountResponse struct {
	value *AvailableLongTermDiscountResponse
	isSet bool
}

func (v NullableAvailableLongTermDiscountResponse) Get() *AvailableLongTermDiscountResponse {
	return v.value
}

func (v *NullableAvailableLongTermDiscountResponse) Set(val *AvailableLongTermDiscountResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableAvailableLongTermDiscountResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableAvailableLongTermDiscountResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAvailableLongTermDiscountResponse(val *AvailableLongTermDiscountResponse) *NullableAvailableLongTermDiscountResponse {
	return &NullableAvailableLongTermDiscountResponse{value: val, isSet: true}
}

func (v NullableAvailableLongTermDiscountResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAvailableLongTermDiscountResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


