/*
SORACOM API

SORACOM API v1

API version: VERSION_PLACEHOLDER
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package api

import (
	"encoding/json"
)

// IndividualInformationModel struct for IndividualInformationModel
type IndividualInformationModel struct {
	AddressLine1 *string `json:"addressLine1,omitempty"`
	AddressLine2 *string `json:"addressLine2,omitempty"`
	Building *string `json:"building,omitempty"`
	City *string `json:"city,omitempty"`
	CountryCode string `json:"countryCode"`
	FullName string `json:"fullName"`
	PhoneNumber string `json:"phoneNumber"`
	State *string `json:"state,omitempty"`
	ZipCode string `json:"zipCode"`
}

// NewIndividualInformationModel instantiates a new IndividualInformationModel object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewIndividualInformationModel(countryCode string, fullName string, phoneNumber string, zipCode string) *IndividualInformationModel {
	this := IndividualInformationModel{}
	this.CountryCode = countryCode
	this.FullName = fullName
	this.PhoneNumber = phoneNumber
	this.ZipCode = zipCode
	return &this
}

// NewIndividualInformationModelWithDefaults instantiates a new IndividualInformationModel object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewIndividualInformationModelWithDefaults() *IndividualInformationModel {
	this := IndividualInformationModel{}
	return &this
}

// GetAddressLine1 returns the AddressLine1 field value if set, zero value otherwise.
func (o *IndividualInformationModel) GetAddressLine1() string {
	if o == nil || o.AddressLine1 == nil {
		var ret string
		return ret
	}
	return *o.AddressLine1
}

// GetAddressLine1Ok returns a tuple with the AddressLine1 field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *IndividualInformationModel) GetAddressLine1Ok() (*string, bool) {
	if o == nil || o.AddressLine1 == nil {
		return nil, false
	}
	return o.AddressLine1, true
}

// HasAddressLine1 returns a boolean if a field has been set.
func (o *IndividualInformationModel) HasAddressLine1() bool {
	if o != nil && o.AddressLine1 != nil {
		return true
	}

	return false
}

// SetAddressLine1 gets a reference to the given string and assigns it to the AddressLine1 field.
func (o *IndividualInformationModel) SetAddressLine1(v string) {
	o.AddressLine1 = &v
}

// GetAddressLine2 returns the AddressLine2 field value if set, zero value otherwise.
func (o *IndividualInformationModel) GetAddressLine2() string {
	if o == nil || o.AddressLine2 == nil {
		var ret string
		return ret
	}
	return *o.AddressLine2
}

// GetAddressLine2Ok returns a tuple with the AddressLine2 field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *IndividualInformationModel) GetAddressLine2Ok() (*string, bool) {
	if o == nil || o.AddressLine2 == nil {
		return nil, false
	}
	return o.AddressLine2, true
}

// HasAddressLine2 returns a boolean if a field has been set.
func (o *IndividualInformationModel) HasAddressLine2() bool {
	if o != nil && o.AddressLine2 != nil {
		return true
	}

	return false
}

// SetAddressLine2 gets a reference to the given string and assigns it to the AddressLine2 field.
func (o *IndividualInformationModel) SetAddressLine2(v string) {
	o.AddressLine2 = &v
}

// GetBuilding returns the Building field value if set, zero value otherwise.
func (o *IndividualInformationModel) GetBuilding() string {
	if o == nil || o.Building == nil {
		var ret string
		return ret
	}
	return *o.Building
}

// GetBuildingOk returns a tuple with the Building field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *IndividualInformationModel) GetBuildingOk() (*string, bool) {
	if o == nil || o.Building == nil {
		return nil, false
	}
	return o.Building, true
}

// HasBuilding returns a boolean if a field has been set.
func (o *IndividualInformationModel) HasBuilding() bool {
	if o != nil && o.Building != nil {
		return true
	}

	return false
}

// SetBuilding gets a reference to the given string and assigns it to the Building field.
func (o *IndividualInformationModel) SetBuilding(v string) {
	o.Building = &v
}

// GetCity returns the City field value if set, zero value otherwise.
func (o *IndividualInformationModel) GetCity() string {
	if o == nil || o.City == nil {
		var ret string
		return ret
	}
	return *o.City
}

// GetCityOk returns a tuple with the City field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *IndividualInformationModel) GetCityOk() (*string, bool) {
	if o == nil || o.City == nil {
		return nil, false
	}
	return o.City, true
}

// HasCity returns a boolean if a field has been set.
func (o *IndividualInformationModel) HasCity() bool {
	if o != nil && o.City != nil {
		return true
	}

	return false
}

// SetCity gets a reference to the given string and assigns it to the City field.
func (o *IndividualInformationModel) SetCity(v string) {
	o.City = &v
}

// GetCountryCode returns the CountryCode field value
func (o *IndividualInformationModel) GetCountryCode() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.CountryCode
}

// GetCountryCodeOk returns a tuple with the CountryCode field value
// and a boolean to check if the value has been set.
func (o *IndividualInformationModel) GetCountryCodeOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.CountryCode, true
}

// SetCountryCode sets field value
func (o *IndividualInformationModel) SetCountryCode(v string) {
	o.CountryCode = v
}

// GetFullName returns the FullName field value
func (o *IndividualInformationModel) GetFullName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.FullName
}

// GetFullNameOk returns a tuple with the FullName field value
// and a boolean to check if the value has been set.
func (o *IndividualInformationModel) GetFullNameOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.FullName, true
}

// SetFullName sets field value
func (o *IndividualInformationModel) SetFullName(v string) {
	o.FullName = v
}

// GetPhoneNumber returns the PhoneNumber field value
func (o *IndividualInformationModel) GetPhoneNumber() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.PhoneNumber
}

// GetPhoneNumberOk returns a tuple with the PhoneNumber field value
// and a boolean to check if the value has been set.
func (o *IndividualInformationModel) GetPhoneNumberOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.PhoneNumber, true
}

// SetPhoneNumber sets field value
func (o *IndividualInformationModel) SetPhoneNumber(v string) {
	o.PhoneNumber = v
}

// GetState returns the State field value if set, zero value otherwise.
func (o *IndividualInformationModel) GetState() string {
	if o == nil || o.State == nil {
		var ret string
		return ret
	}
	return *o.State
}

// GetStateOk returns a tuple with the State field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *IndividualInformationModel) GetStateOk() (*string, bool) {
	if o == nil || o.State == nil {
		return nil, false
	}
	return o.State, true
}

// HasState returns a boolean if a field has been set.
func (o *IndividualInformationModel) HasState() bool {
	if o != nil && o.State != nil {
		return true
	}

	return false
}

// SetState gets a reference to the given string and assigns it to the State field.
func (o *IndividualInformationModel) SetState(v string) {
	o.State = &v
}

// GetZipCode returns the ZipCode field value
func (o *IndividualInformationModel) GetZipCode() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ZipCode
}

// GetZipCodeOk returns a tuple with the ZipCode field value
// and a boolean to check if the value has been set.
func (o *IndividualInformationModel) GetZipCodeOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.ZipCode, true
}

// SetZipCode sets field value
func (o *IndividualInformationModel) SetZipCode(v string) {
	o.ZipCode = v
}

func (o IndividualInformationModel) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.AddressLine1 != nil {
		toSerialize["addressLine1"] = o.AddressLine1
	}
	if o.AddressLine2 != nil {
		toSerialize["addressLine2"] = o.AddressLine2
	}
	if o.Building != nil {
		toSerialize["building"] = o.Building
	}
	if o.City != nil {
		toSerialize["city"] = o.City
	}
	if true {
		toSerialize["countryCode"] = o.CountryCode
	}
	if true {
		toSerialize["fullName"] = o.FullName
	}
	if true {
		toSerialize["phoneNumber"] = o.PhoneNumber
	}
	if o.State != nil {
		toSerialize["state"] = o.State
	}
	if true {
		toSerialize["zipCode"] = o.ZipCode
	}
	return json.Marshal(toSerialize)
}

type NullableIndividualInformationModel struct {
	value *IndividualInformationModel
	isSet bool
}

func (v NullableIndividualInformationModel) Get() *IndividualInformationModel {
	return v.value
}

func (v *NullableIndividualInformationModel) Set(val *IndividualInformationModel) {
	v.value = val
	v.isSet = true
}

func (v NullableIndividualInformationModel) IsSet() bool {
	return v.isSet
}

func (v *NullableIndividualInformationModel) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableIndividualInformationModel(val *IndividualInformationModel) *NullableIndividualInformationModel {
	return &NullableIndividualInformationModel{value: val, isSet: true}
}

func (v NullableIndividualInformationModel) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableIndividualInformationModel) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


